name: Staging CI

on: pull_request

jobs:
  ci:
    uses: TogetherCrew/operations/.github/workflows/ci.yml@main
    secrets:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
